
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  annotations:
    # Specify the cluster issuer created previously to use for the ingress
    cert-manager.io/cluster-issuer: letsencrypt-nginx-cert
spec:
  tls:
    - hosts:
      # Specify the hosts to use for the ingress - same as the host in the ingress resource
      - www.samsarian.com
      # Specify the secret name to use for the ingress - this will be dynamically created by cert-manager
      secretName: letsencrypt-nginx-cert-samsarian
  ingressClassName: nginx
  rules:
    - host: www.samsarian.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
            path: /