apiVersion: v1
kind: Pod
metadata:
  labels:
    run: new-pod
  name: new-pod
spec:
  containers:
  - image: nginx
    name: new-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
